version: "3.9"

services:
  crontab:
    build: .
    volumes:
      - "./jobs/:/talendinfra/jobs"
      - "./scripts/:/talendinfra/scripts"
      - "./data/:/talendinfra/data/"

    networks:
      - database

  mariadb:
    image: mariadb:10.7
    ports:
      - 3306:3306

    volumes:
      - "./config/mariadb:/var/lib/mysql"

    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=mysql
      - MYSQL_USER=mysql
      - MYSQL_DATABASE=data

    restart: on-failure

    networks:
      - database

networks:
  database:
    external: true