version: "3.9"

services:

  crontab:
    build: .
    volumes:
      - "./jobs/:/talendinfra/jobs"
      - "./scripts/:/talendinfra/scripts"
      - "./data/:/talendinfra/data/"
    networks:
      - database

  mariadb:
    image: mariadb:10.7
    ports:
      - 3306:3306
    volumes:
      - "./config/mariadb:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=mysql
      - MYSQL_USER=mysql
      - MYSQL_DATABASE=data
    restart: on-failure
    networks:
      - database

  pureftp:
    image: stilliard/pure-ftpd
    ports:
      - 21:21
      - 22:22
      - 30000-30009:30000-30009
    environment:
      - PUBLICHOST=localhost
      - FTP_USER_NAME=user
      - FTP_USER_PASS=user
      - FTP_USER_HOME=/home/user
    networks:
      - database

networks:
  database:
    external: true